services:
  - type: web
    name: etsiibot
    runtime: docker
    dockerfile: Dockerfile
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: TOKEN
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
    autoDeploy: true
